### ISSUE TITLE
Hey how to use it , no implementation no jar? 

### ISSUE THREAD

**Issue by GuyDviri** [lovejjfg/ShadowCircleImageView#1]

**Comment by lovejjfg** [comment]
I'm sorry,This is a [MR](https://github.com/hdodenhof/CircleImageView/pull/212) to  [CircleImageView](https://github.com/hdodenhof/CircleImageView) but closed, so I haven't released any version. as i know, the  [CircleImageView](https://github.com/hdodenhof/CircleImageView)  have supported shadow in version 2.2, so you'd better to have a try on that. if you want to support `Drawable` ,emm, i'll think about release a version.😼

**Comment by GuyDviri** [comment]
Hey , the shader on CircleImageView is nothing like yours.
Please let me know when you have news.

**Comment by lovejjfg** [comment]
now you can get it in  jcenter()
 `compile 'com.lovejjfg:circleimageview:0.0.1-beta'`

**Comment by GuyDviri** [comment]
Thanks but it's bring an error :

**Comment by GuyDviri** [comment]
AGPBI: {"kind":"error","text":"Program type already present:
com.dd.CircularAnimatedDrawable$1","sources":[{}],"tool":"D8"}
java.lang.RuntimeException:
com.android.builder.dexing.DexArchiveMergerException: Error while merging
dex archives:
D:\Programming\minddates\app\build\intermediates\transforms\dexBuilder\release\0,
D:\Programming\minddates\app\build\intermediates\transforms\externalLibsDexMerger\release\0,
D:\Programming\minddates\app\build\intermediates\transforms\dexBuilder\release\1.jar,
D:\Programming\minddates\app\build\intermediates\transforms\dexBuilder\release\2.jar,
D:\Programming\minddates\app\build\intermediates\transforms\dexBuilder\release\3.jar,

**Comment by GuyDviri** [comment]
AGPBI: {"kind":"error","text":"Program type already present:
com.dd.CircularAnimatedDrawable$1","sources":[{}],"tool":"D8"}
java.lang.RuntimeException:
com.android.builder.dexing.DexArchiveMergerException: Error while merging
dex archives: app\build\intermediates\transforms\dexBuilder\release\0,
\app\build\intermediates\transforms\externalLibsDexMerger\release\0,
D:\Programming\minddates\app\build\intermediates\transforms\dexBuilder\release\1.jar,
app\build\intermediates\transforms\dexBuilder\release\2.jar,
s\app\build\intermediates\transforms\dexBuilder\release\3.jar,

**Comment by GuyDviri** [comment]
somehow it's doesn't work :

 Glide.with(getContext())
        .load(url)
        .dontAnimate()
        .placeholder(R.drawable.shape_empt_night)
        .error(R.drawable.ic_launcher)
        .into(mIv);

maybe you can check it out via teamview .. I really like to use yours
shadder..
please let me know via hangouts..

thanks alot

Guy
